services:
  web:
    build:
      dockerfile: Dockerfile
    container_name: bde-platform
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - bdd
    command: sh -c "composer install && php -S 0.0.0.0:80 -t public/ public/index.php"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_HOST=${MARIADB_HOST}
    
  bdd:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./sql-dumps/createdb.sql:/docker-entrypoint-initdb.d/bdd.sql
      - db_data:/var/lib/mysql
volumes:
  db_data:
